development:
  adapter: postgresql
  encoding: unicode
  database: angulartodolist_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: angulartodolist_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: angulartodolist_production
  pool: 5
  username: postgres
  password: password
